### ISSUE TITLE
Request: Ability to add Custom LUA SDK 

### ISSUE THREAD

**Issue by vipexv** [EmmyLua/Intellij-EmmyLua2#1]
![image](https://github.com/user-attachments/assets/fefa5b04-cca4-4ad1-9cb0-e8e22401a629)

When using the other EmmyLua i could add SDK's, which i would prefer to do since i need it for my FiveM natives classnames, but the other version doesn't support the LUA Version FiveM uses and this does.

**Comment by CppCXY** [comment]
see https://github.com/CppCXY/EmmyLuaAnalyzer/blob/master/docs/.emmyrc.json_EN.md

**Comment by CppCXY** [comment]
If you are using FiveM, its syntax differs from standard Lua. EmmyLua does not support non-standard Lua syntax, so it is better to use Sumneko Lua.

**Comment by vipexv** [comment]
Sumneko Lua Doesn't support adding SDK's in Intellij, so the only way i found around that is to just grab all of the natives definitions and add them locally to the folder so it loads them.

You can do the same thing in EmmyLua2 and that's working well for me, i was just wondering if i could just use the SDK as that was allot better.

Also EmmyLua2 seems to be working quite well, it detects the modules which the other version didn't.

also when i do

```local functionName = function()

end```

the other EmmyLua didn't support that but this one does.

**Comment by vipexv** [comment]
![image](https://github.com/user-attachments/assets/abe090f3-c932-42de-a8ae-1d2bc12f044f)

So adding the FiveM natives/funcs in the definitions folder works but it's not the best solution.

**Comment by CppCXY** [comment]
you can just set this in .emmyrc.json :
```json
{
    "workspace" : {
        "library": "path/to/sdk"
    }
}
```

**Comment by vipexv** [comment]
Yeah that's what i just did, thank you once again and i really appreciate it!
