### ISSUE TITLE
Excluded directories/files are not ignored

### ISSUE THREAD

**Issue by BreakBB** [EmmyLua/Intellij-EmmyLua2#9]
We do have a "releases" directory in our project where copies of most modules are moved to on build. This plugin does not ignore these directories for the reference check, so that "Go to Declaration or Usage" is unusable as it jumps to the ignored files.

**Comment by CppCXY** [comment]
Please use the .emmyrc configuration, because this plugin is actually a port of vscode-emmylua. Its main analysis logic is implemented in C#, making it difficult to read the configuration from IntelliJ.
